version: '3'
services:
  kafka:
    image: bitnami/kafka:3.4
    volumes:
      - kafka_data:/bitnami
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

  central-station:
    image: central-station
    ports:
      - 8082:8082
    volumes:
      - central_station_data:/app/data
    environment:
      - kafka=kafka
    depends_on:
      - kafka

  weather-station:
    image: weather-station
    environment:
      - kafka=kafka
    depends_on:
      - kafka

volumes:
  kafka_data:
  central_station_data:
