apiVersion: v1
kind: Pod
metadata:
  name: central-station
  labels:
    app: weather-monitor
    type: central-station
spec:
  containers:
    - name: central-station
      image: central-station:latest
      imagePullPolicy: Never
      env:
        - name: kafka
          value: kafka-service
        - name: elastic_search
          value: elastic-service
        - name: data_path
          value: /app/data
      volumeMounts:
        - name: data-volume
          mountPath: /app/data
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: pvc
