apiVersion: v1
kind: Pod
metadata:
  name: central-station
  labels:
    app: weather-monitor
    type: central-station
spec:
  containers:
    - name: central-station
      image: central-station:latest
      imagePullPolicy: Never
      env:
        - name: kafka
          value: kafka-service
  restartPolicy: Never
