apiVersion: v1
kind: Service
metadata:
  name: central-service
spec:
  type: NodePort
  selector:
    app: weather-monitor
    type: central-station
  ports:
    - name: bitcask
      port: 8082
      targetPort: 8082
      nodePort: 30004
