apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: weather-station-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-monitor
      type: weather-station
  template:
    metadata:
      name: weather-station
      labels:
        app: weather-monitor
        type: weather-station
    spec:
      containers:
        - name: weather-station
          image: weather-station
          imagePullPolicy: Never
          env:
          - name: kafka
            value: "kafka-service"
